/// Flutter icons Tambalin
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Tambalin
///      fonts:
///       - asset: fonts/Tambalin.ttf
///
/// 
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class Tambalin {
  

  Tambalin._();

  static const _kFontFam = 'Tambalin';
  static const String? _kFontPkg = null;

  static const IconData col_view = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData col_view_2 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_dropdown = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_dropup = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left_navgation = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blacklist = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contact = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData current_location = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData current_location_2 = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData distance = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorites = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fire = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData food = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData friends = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gas = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hotel = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData id_contact = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData level = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData matched = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu_2 = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menubar = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_2 = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nearby = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData order = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData place = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData promo = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData report = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rewinds = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData security = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send_eta = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData speed = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tags = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vehicle = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData videos = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vip_center = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visitor = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}